# Based on ripgrep's release action:
# https://github.com/BurntSushi/ripgrep/blob/master/.github/workflows/release.yml

name: Build Release Binaries
on:
  release:
    types: [published]

jobs:
  build-release:
    name: release ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
#        - target: x86_64-unknown-linux-musl
#          os: ubuntu-latest
#          cross: true
#        - target: aarch64-unknown-linux-musl
#          os: ubuntu-latest
#          cross: true
#        - target: armv7-unknown-linux-musleabi
#          os: ubuntu-latest
#          cross: true
        - target: aarch64-apple-darwin
          os: macos-latest
          cross: false

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        target: ${{ matrix.target }}
    - uses: Swatinem/rust-cache@v2

    - uses: awalsh128/cache-apt-pkgs-action@latest
      if: ${{ matrix.cross }}
      with:
        packages: libasound2-dev libssl-dev
        version: 1.0

    - name: Run Cross
      if: ${{ matrix.cross }}
      run: |
        cargo install cross --git https://github.com/cross-rs/cross.git
        cross build --release --target ${{ matrix.target }}

    - name: Run Cargo
      if: ${{ !matrix.cross }}
      run: |
        cargo build --release --target ${{ matrix.target }}
        cargo build --release --target ${{ matrix.target }} --bin gwrust-generate_tones --features="generate_tones"

    - name: create artifact directory
      shell: bash
      run: |
        directory=gwrust-${{ matrix.target }}
        mkdir $directory
        #        cp README.md LICENSE NOTICE $directory
        cp target/${{ matrix.target }}/release/gwrust $directory
        cp target/${{ matrix.target }}/release/gwrust-generate_tones $directory
        tar cJf $directory.tar.xz $directory

    - uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: "gwrust-${{ matrix.target }}.*"
        allowUpdates: true
        omitNameDuringUpdate: true
        omitBodyDuringUpdate: true

